# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '多图下载' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 多图下载
  pod 'MJExtension'
  pod 'SDWebImage'
end
